<a href="https://colab.research.google.com/github/AR-Ashik-9997/Phitron-practice-problem/blob/main/Deep_learning_concept_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
X = torch.tensor([[1.0, 2.0], [2.0, 3.0]], dtype=torch.float32)
y_true = torch.tensor([[1.0], [0.0]], dtype=torch.float32)

print("--- Step 1: Input Data ---")
print("Input Features (X):\n", X)
print("True Targets (y):\n", y_true)

--- Step 1: Input Data ---
Input Features (X):
 tensor([[1., 2.],
        [2., 3.]])
True Targets (y):
 tensor([[1.],
        [0.]])


In [ ]:
class SimpleNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        # Input: 2, Hidden: 3, Output: 1
        self.hidden_layer = nn.Linear(in_features=2, out_features=3)
        self.activation = nn.ReLU()  # Activation Function
        self.output_layer = nn.Linear(in_features=3, out_features=1)
        self.sigmoid = nn.Sigmoid()  # Output Activation (Probability)

    def forward(self, x):
        h = self.activation(self.hidden_layer(x))
        out = self.sigmoid(self.output_layer(h))
        return out

model = SimpleNeuralNetwork()

print("\n--- Step 2: Model Architecture ---")
print(model)


--- Step 2: Model Architecture ---
SimpleNeuralNetwork(
  (hidden_layer): Linear(in_features=2, out_features=3, bias=True)
  (activation): ReLU()
  (output_layer): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [ ]:
# Forward Propagation and Loss Function
criterion = nn.MSELoss()
y_pred = model(X)
loss = criterion(y_pred, y_true)

print("\n--- Step 3: Forward Pass & Initial Loss ---")
print("Initial Predictions (y_pred):\n", y_pred.detach())
print("Initial Loss Value:", loss.item())


--- Step 3: Forward Pass & Initial Loss ---
Initial Predictions (y_pred):
 tensor([[0.4412],
        [0.4581]])
Initial Loss Value: 0.2610359787940979


In [ ]:
# Backpropagate gradients
loss.backward()
print("\n--- Step 4: Backpropagation (Gradients) ---")
print("Hidden Layer Weight Gradients:\n", model.hidden_layer.weight.grad)


--- Step 4: Backpropagation (Gradients) ---
Hidden Layer Weight Gradients:
 tensor([[-0.0210, -0.0154],
        [ 0.0343,  0.0251],
        [ 0.0000,  0.0000]])


In [ ]:
torch.manual_seed(42)

# Optimizer
optimizers_dict = {
    "1. Standard SGD": lambda params: optim.SGD(params, lr=0.1),
    "2. SGD with Momentum": lambda params: optim.SGD(params, lr=0.1, momentum=0.9),
    "3. RMSprop": lambda params: optim.RMSprop(params, lr=0.1),
    "4. Adam": lambda params: optim.Adam(params, lr=0.1)
}

criterion = nn.MSELoss()

print("--- Comparison of Different Optimizers ---\n")

for name, opt_func in optimizers_dict.items():
    torch.manual_seed(42)
    model = SimpleNeuralNetwork()
    optimizer = opt_func(model.parameters())

    # Forward Pass & Loss
    y_pred = model(X)
    loss = criterion(y_pred, y_true)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()

    # befor older weight
    initial_weights = model.hidden_layer.weight.clone().detach()

    # Optimizer update
    optimizer.step()

    # updated after weight
    updated_weights = model.hidden_layer.weight.clone().detach()

    print(f"=== {name} ===")
    print("Initial Loss:", round(loss.item(), 5))
    print("\n\n Weights BEFORE update:", initial_weights.numpy())
    print("\n Weights AFTER update:", updated_weights.numpy())
    print("-" * 45)

--- Comparison of Different Optimizers ---

=== 1. Standard SGD ===
Initial Loss: 0.24387


 Weights BEFORE update: [[ 0.5406104   0.5869042 ]
 [-0.16565566  0.6495563 ]
 [-0.15492962  0.14268756]]

 Weights AFTER update: [[ 0.5498459   0.59920704]
 [-0.17659777  0.63498   ]
 [-0.15728574  0.13954893]]
---------------------------------------------
=== 2. SGD with Momentum ===
Initial Loss: 0.24387


 Weights BEFORE update: [[ 0.5406104   0.5869042 ]
 [-0.16565566  0.6495563 ]
 [-0.15492962  0.14268756]]

 Weights AFTER update: [[ 0.5498459   0.59920704]
 [-0.17659777  0.63498   ]
 [-0.15728574  0.13954893]]
---------------------------------------------
=== 3. RMSprop ===
Initial Loss: 0.24387


 Weights BEFORE update: [[ 0.5406104   0.5869042 ]
 [-0.16565566  0.6495563 ]
 [-0.15492962  0.14268756]]

 Weights AFTER update: [[ 1.5406092   1.5869033 ]
 [-1.1656547  -0.350443  ]
 [-1.1549255  -0.85730934]]
---------------------------------------------
=== 4. Adam ===
Initial Loss: 0.24387


In [ ]:
def create_sgd(params):
    return optim.SGD(params, lr=0.1)