<a href="https://colab.research.google.com/github/AR-Ashik-9997/Phitron-practice-problem/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import torch

In [25]:
X = torch.tensor([[1.0, 2.0]])
W = torch.tensor([[0.5],
                 [0.3]])
b = torch.tensor([[0.1]])

In [26]:
# shapes of X, W, and b
print(f"shapes of {X.shape}\n {W.shape}\n {b.shape}")

shapes of torch.Size([1, 2])
 torch.Size([2, 1])
 torch.Size([1, 1])


# Will torch.matmul(X, W) work? Why?

because W is Transport

In [27]:
torch.matmul(X, W)

tensor([[1.1000]])

In [28]:
X = torch.tensor([[1.0, 2.0]])
W1 = torch.tensor([[0.5, -0.2, 0.1], [0.3, 0.8, -0.5]])
b1 = torch.tensor([[0.1, 0.0, -0.1]])
W2 = torch.tensor([[0.7], [0.2], [-0.4]])
b2 = torch.tensor([[0.05]])

Z1=torch.matmul(X,W1)+b1
A1=torch.relu(Z1)
Z2=torch.matmul(A1,W2)+b2

print("Layer 1 Pre-activation (Z1):", Z1)
print("Layer 1 Post-activation (A1):", A1)
print("Final Output (Z2):", Z2)

Layer 1 Pre-activation (Z1): tensor([[ 1.2000,  1.4000, -1.0000]])
Layer 1 Post-activation (A1): tensor([[1.2000, 1.4000, 0.0000]])
Final Output (Z2): tensor([[1.1700]])


In [29]:
X=torch.tensor([[1.0],[2.0]])
W1=torch.tensor([[0.1,0.2],[0.3,0.4]])
b1 = torch.tensor([[0.1,-0.1]])
W2=torch.tensor([[0.7,0.4]])
b2=torch.tensor([[0.05]])

In [39]:
Z1=torch.matmul(W1,X)+b1
A1=torch.relu(Z1)
y_hat=torch.matmul(W2,A1)+b2

print(f"Z1:\n{Z1}")
print(f"\nA1:\n{A1}")
print(f"\ny_hat:\n{y_hat}")

Z1:
tensor([[0.5000, 0.5000],
        [1.1000, 1.1000]])

A1:
tensor([[0.5000, 0.5000],
        [1.1000, 1.1000]])

y_hat:
tensor([[0.7900, 0.7900],
        [0.7900, 0.7900]])


If all weights are initialized to 0.1 and biases are zero, compute the final output manually for input X = [[1.0], [2.0]].

In [43]:
x=torch.tensor([[1.0], [2.0]])
w1=torch.full((2,2),0.1)
w2=torch.full((1,2),0.1)
b1=torch.zeros((2,1))
b2=torch.zeros((1,1))

z1=torch.matmul(w1,x)+b1
a1=torch.relu(z1)
y_hat=torch.matmul(w2,a1)+b2

y_hat

tensor([[0.0600]])